import FlashcardSession from "../../components/FlashcardSession.jsx";

export default function FlashcardsPage() {
  return (
    <>
      <h1>Flashcards</h1>
      <p className="lede">
        Spaced repetition over key points, provisions, and mnemonics you've already generated by visiting
        Teach/Grasp — nothing new is generated here, cards just come back on a schedule tuned to how well you
        recalled them last time.
      </p>
      <FlashcardSession />
    </>
  );
}
