// db/seed/essay-topics.js
//
// The Essay paper's topic bank -- 500+ topics, split honestly into two
// kinds (see essayTopics.source in db/schema.js), NEVER conflated:
//
// - source:'pyq'  -- REAL UPSC Essay paper topics, 1993-2025, transcribed
//   from public compilations of official past papers (verified against
//   multiple independent sources during research). `year` is set.
// - source:'guidance' -- practice topics compiled from public UPSC
//   coaching-guidance sources (theme-wise "important topics" and
//   "expected/likely topics" lists) -- NOT real past exam questions, never
//   presented as one. `year` is null.
//
// `category` is a thematic browsing label, independent of `source`.
// category for real PYQs is assigned by a keyword heuristic (a browsing
// convenience, not scored content) rather than hand-tagged one by one;
// category for guidance topics is preserved from how the source itself
// grouped them.
//
// This deliberately does NOT include per-topic "master content" -- see
// essay_guides in db/schema.js and app/api/essay-guide/route.js: planning
// guidance is generated once per topic on first view (same lazy,
// generate-once-reuse-forever pattern as lessons.teachContent), not
// pre-authored for 500+ topics up front.
export const essayTopicsSeed = [
  { id: "essay-1993-1", topicText: "My vision of India in 2001 a.d.", category: "Philosophy & Values", source: "pyq", year: 1993 },
  { id: "essay-1993-2", topicText: "Compassion is the basic of all morality of the world", category: "Philosophy & Values", source: "pyq", year: 1993 },
  { id: "essay-1993-3", topicText: "Economic growth without distributive justice is bound to breed violence", category: "Economy", source: "pyq", year: 1993 },
  { id: "essay-1993-4", topicText: "Men have failed: let women take over", category: "Women & Gender", source: "pyq", year: 1993 },
  { id: "essay-1993-5", topicText: "Computer: the harbinger of silent revolution", category: "Science and Technology", source: "pyq", year: 1993 },
  { id: "essay-1993-6", topicText: "He who reigns within himself and rules his passions and desires is more than a king", category: "Philosophy & Values", source: "pyq", year: 1993 },
  { id: "essay-1994-1", topicText: "The Indian society at the crossroads", category: "Society and Social Justice", source: "pyq", year: 1994 },
  { id: "essay-1994-2", topicText: "Politics, bureaucracy and business – fatal triangle", category: "Polity and Governance", source: "pyq", year: 1994 },
  { id: "essay-1994-3", topicText: "Multinational corporations – saviours or saboteurs", category: "Philosophy & Values", source: "pyq", year: 1994 },
  { id: "essay-1994-4", topicText: "Modernisation and westernisation are not identical concepts", category: "Philosophy & Values", source: "pyq", year: 1994 },
  { id: "essay-1994-5", topicText: "Youth is a blunder, manhood a struggle, old age a regret", category: "Society and Social Justice", source: "pyq", year: 1994 },
  { id: "essay-1995-1", topicText: "Whither Indian democracy?", category: "Polity and Governance", source: "pyq", year: 1995 },
  { id: "essay-1995-2", topicText: "Politics without ethics is a disaster", category: "Environment", source: "pyq", year: 1995 },
  { id: "essay-1995-3", topicText: "Disinterested intellectual curiosity is the lifeblood of civilisation", category: "Culture and Media", source: "pyq", year: 1995 },
  { id: "essay-1995-4", topicText: "The new emerging women power", category: "Women & Gender", source: "pyq", year: 1995 },
  { id: "essay-1995-5", topicText: "Restructuring of Indian education system", category: "Education", source: "pyq", year: 1995 },
  { id: "essay-1996-1", topicText: "The VIP cult is a bane of Indian democracy", category: "Polity and Governance", source: "pyq", year: 1996 },
  { id: "essay-1996-2", topicText: "Need for transparency in public administration", category: "Polity and Governance", source: "pyq", year: 1996 },
  { id: "essay-1996-3", topicText: "New cults and godmen: a threat to traditional religion", category: "Culture and Media", source: "pyq", year: 1996 },
  { id: "essay-1996-4", topicText: "Literacy is growing very fast, but there is no corresponding growth in education", category: "Economy", source: "pyq", year: 1996 },
  { id: "essay-1996-5", topicText: "Truth is lived, not taught", category: "Philosophy & Values", source: "pyq", year: 1996 },
  { id: "essay-1997-1", topicText: "What we have not learnt during fifty years of independence", category: "Philosophy & Values", source: "pyq", year: 1997 },
  { id: "essay-1997-2", topicText: "Judicial activism", category: "Polity and Governance", source: "pyq", year: 1997 },
  { id: "essay-1997-3", topicText: "Greater political power alone will not improve women's plight", category: "Women & Gender", source: "pyq", year: 1997 },
  { id: "essay-1997-4", topicText: "Urbanization is a blessing in disguise", category: "Society and Social Justice", source: "pyq", year: 1997 },
  { id: "essay-1997-5", topicText: "The modern doctor and his patients", category: "Philosophy & Values", source: "pyq", year: 1997 },
  { id: "essay-1998-1", topicText: "The language problem in India", category: "Philosophy & Values", source: "pyq", year: 1998 },
  { id: "essay-1998-2", topicText: "The composite culture of India", category: "Culture and Media", source: "pyq", year: 1998 },
  { id: "essay-1998-3", topicText: "Woman is god's best creation", category: "Women & Gender", source: "pyq", year: 1998 },
  { id: "essay-1998-4", topicText: "India's contribution to world wisdom", category: "Philosophy & Values", source: "pyq", year: 1998 },
  { id: "essay-1998-5", topicText: "The world of the twenty-first century", category: "Philosophy & Values", source: "pyq", year: 1998 },
  { id: "essay-1999-1", topicText: "Resource management in the Indian context", category: "Philosophy & Values", source: "pyq", year: 1999 },
  { id: "essay-1999-2", topicText: "Youth culture today", category: "Culture and Media", source: "pyq", year: 1999 },
  { id: "essay-1999-3", topicText: "Mass media and cultural invasion", category: "Culture and Media", source: "pyq", year: 1999 },
  { id: "essay-1999-4", topicText: "Reservation, politics and empowerment", category: "Polity and Governance", source: "pyq", year: 1999 },
  { id: "essay-1999-5", topicText: "Women empowerment: challenges and prospects", category: "Women & Gender", source: "pyq", year: 1999 },
  { id: "essay-2000-1", topicText: "Why should we be proud of being Indians?", category: "Philosophy & Values", source: "pyq", year: 2000 },
  { id: "essay-2000-2", topicText: "Indian culture today: a myth or a reality?", category: "Culture and Media", source: "pyq", year: 2000 },
  { id: "essay-2000-3", topicText: "The cyberworld: its charms and challenges", category: "Science and Technology", source: "pyq", year: 2000 },
  { id: "essay-2000-4", topicText: "The country's need for a better disaster management system", category: "Environment", source: "pyq", year: 2000 },
  { id: "essay-2000-5", topicText: "The implications of globalization for India", category: "International Relations", source: "pyq", year: 2000 },
  { id: "essay-2001-1", topicText: "Empowerment alone cannot help our women", category: "Women & Gender", source: "pyq", year: 2001 },
  { id: "essay-2001-2", topicText: "My vision of an ideal world order", category: "International Relations", source: "pyq", year: 2001 },
  { id: "essay-2001-3", topicText: "The march of science and the erosion of human values", category: "Science and Technology", source: "pyq", year: 2001 },
  { id: "essay-2001-4", topicText: "The pursuit of excellence", category: "Philosophy & Values", source: "pyq", year: 2001 },
  { id: "essay-2001-5", topicText: "Irrelevance of the classroom", category: "Education", source: "pyq", year: 2001 },
  { id: "essay-2002-1", topicText: "Responsibility of media in a democracy", category: "Culture and Media", source: "pyq", year: 2002 },
  { id: "essay-2002-2", topicText: "Privatization of higher education in India", category: "Education", source: "pyq", year: 2002 },
  { id: "essay-2002-3", topicText: "If youth knew, if age could", category: "Society and Social Justice", source: "pyq", year: 2002 },
  { id: "essay-2002-4", topicText: "Search for truth can only be a spiritual problem", category: "Philosophy & Values", source: "pyq", year: 2002 },
  { id: "essay-2002-5", topicText: "Modern technological education and human values", category: "Education", source: "pyq", year: 2002 },
  { id: "essay-2003-1", topicText: "How should a civil servant conduct himself?", category: "Polity and Governance", source: "pyq", year: 2003 },
  { id: "essay-2003-2", topicText: "The masks of new imperialism", category: "International Relations", source: "pyq", year: 2003 },
  { id: "essay-2003-3", topicText: "Spirituality and scientific temper", category: "Philosophy & Values", source: "pyq", year: 2003 },
  { id: "essay-2003-4", topicText: "There is nothing either good or bad but thinking makes it so", category: "Philosophy & Values", source: "pyq", year: 2003 },
  { id: "essay-2003-5", topicText: "As civilization advances culture declines", category: "Culture and Media", source: "pyq", year: 2003 },
  { id: "essay-2004-1", topicText: "Water resources should be under the control of the central government", category: "Environment", source: "pyq", year: 2004 },
  { id: "essay-2004-2", topicText: "Judicial activism and Indian democracy", category: "Polity and Governance", source: "pyq", year: 2004 },
  { id: "essay-2004-3", topicText: "Whither women's emancipation?", category: "Women & Gender", source: "pyq", year: 2004 },
  { id: "essay-2004-4", topicText: "Globalizations and its impact on Indian culture", category: "International Relations", source: "pyq", year: 2004 },
  { id: "essay-2004-5", topicText: "The lure of space", category: "Science and Technology", source: "pyq", year: 2004 },
  { id: "essay-2005-1", topicText: "Justice must reach the poor", category: "Society and Social Justice", source: "pyq", year: 2005 },
  { id: "essay-2005-2", topicText: "If women ruled the world", category: "Women & Gender", source: "pyq", year: 2005 },
  { id: "essay-2005-3", topicText: "Food security for sustainable national development", category: "Philosophy & Values", source: "pyq", year: 2005 },
  { id: "essay-2005-4", topicText: "Terrorism and world peace", category: "International Relations", source: "pyq", year: 2005 },
  { id: "essay-2005-5", topicText: "What is real education?", category: "Education", source: "pyq", year: 2005 },
  { id: "essay-2006-1", topicText: "Cyberspace and Internet: Blessing or curse", category: "Science and Technology", source: "pyq", year: 2006 },
  { id: "essay-2006-2", topicText: "Protection of ecology and environment is essential for sustained economic development", category: "Environment", source: "pyq", year: 2006 },
  { id: "essay-2006-3", topicText: "\"Education for all\" campaign in India: myth or reality", category: "Education", source: "pyq", year: 2006 },
  { id: "essay-2006-4", topicText: "Globalization would finish small-scale industries in India", category: "Economy", source: "pyq", year: 2006 },
  { id: "essay-2006-5", topicText: "Importance of Indo-US nuclear agreement", category: "International Relations", source: "pyq", year: 2006 },
  { id: "essay-2007-1", topicText: "Is autonomy the best answer to combat balkanization?", category: "Philosophy & Values", source: "pyq", year: 2007 },
  { id: "essay-2007-2", topicText: "How has satellite television brought about cultural change in Indian mindsets?", category: "Science and Technology", source: "pyq", year: 2007 },
  { id: "essay-2007-3", topicText: "Independent thinking should be encouraged right from the childhood", category: "Philosophy & Values", source: "pyq", year: 2007 },
  { id: "essay-2007-4", topicText: "BPO boom in India", category: "Economy", source: "pyq", year: 2007 },
  { id: "essay-2007-5", topicText: "Evaluation of panchayati raj system", category: "Polity and Governance", source: "pyq", year: 2007 },
  { id: "essay-2008-1", topicText: "Urbanization and its hazards", category: "Society and Social Justice", source: "pyq", year: 2008 },
  { id: "essay-2008-2", topicText: "Role of media in good governance", category: "Culture and Media", source: "pyq", year: 2008 },
  { id: "essay-2008-3", topicText: "Is an egalitarian society possible by educating the masses?", category: "Society and Social Justice", source: "pyq", year: 2008 },
  { id: "essay-2008-4", topicText: "Discipline means success, anarchy means ruin", category: "Philosophy & Values", source: "pyq", year: 2008 },
  { id: "essay-2008-5", topicText: "National identity and patriotism", category: "Philosophy & Values", source: "pyq", year: 2008 },
  { id: "essay-2009-1", topicText: "Are we a 'soft' state?", category: "Philosophy & Values", source: "pyq", year: 2009 },
  { id: "essay-2009-2", topicText: "Good fences make good neighbours", category: "International Relations", source: "pyq", year: 2009 },
  { id: "essay-2009-3", topicText: "The focus of health care is increasingly getting skewed towards the 'haves' of our society", category: "Society and Social Justice", source: "pyq", year: 2009 },
  { id: "essay-2009-4", topicText: "'Globalization' vs. 'Nationalism'", category: "International Relations", source: "pyq", year: 2009 },
  { id: "essay-2009-5", topicText: "Are our traditional handicrafts doomed to a slow death?", category: "Economy", source: "pyq", year: 2009 },
  { id: "essay-2010-1", topicText: "From traditional Indian philanthropy to the gates-buffet model — a natural progression or a paradigm shift?", category: "Philosophy & Values", source: "pyq", year: 2010 },
  { id: "essay-2010-2", topicText: "Geography may remain the same; history need not", category: "Philosophy & Values", source: "pyq", year: 2010 },
  { id: "essay-2010-3", topicText: "Should a moratorium be imposed on all fresh mining in tribal areas of the country?", category: "Environment", source: "pyq", year: 2010 },
  { id: "essay-2010-4", topicText: "Preparedness of our society for India's global leadership role", category: "International Relations", source: "pyq", year: 2010 },
  { id: "essay-2011-1", topicText: "Creation of smaller states and the consequent administrative, economic and developmental implications", category: "Economy", source: "pyq", year: 2011 },
  { id: "essay-2011-2", topicText: "Does Indian cinema shape our popular culture or merely reflect it?", category: "Culture and Media", source: "pyq", year: 2011 },
  { id: "essay-2011-3", topicText: "In the Indian context, both human intelligence and technical intelligence are crucial in combating terrorism", category: "International Relations", source: "pyq", year: 2011 },
  { id: "essay-2011-4", topicText: "Credit-based higher education system — status, opportunities and challenges", category: "Education", source: "pyq", year: 2011 },
  { id: "essay-2012-1", topicText: "In the context of Gandhiji's views, explore the terms 'Swadhinata', 'Swaraj' and 'Dharmarajya'. Critically comment on their contemporary relevance", category: "Polity and Governance", source: "pyq", year: 2012 },
  { id: "essay-2012-2", topicText: "Science and Mysticism: Are they compatible?", category: "Science and Technology", source: "pyq", year: 2012 },
  { id: "essay-2012-3", topicText: "Is the criticism that the 'Public-Private-Partnership' (PPP) model for development is more of a bane than a boon, justified?", category: "Philosophy & Values", source: "pyq", year: 2012 },
  { id: "essay-2012-4", topicText: "Managing work and home – is the Indian working woman getting a fair deal?", category: "Women & Gender", source: "pyq", year: 2012 },
  { id: "essay-2013-1", topicText: "Be the change you want to see in others", category: "Philosophy & Values", source: "pyq", year: 2013 },
  { id: "essay-2013-2", topicText: "Is the Colonial mentality hindering India's success?", category: "Philosophy & Values", source: "pyq", year: 2013 },
  { id: "essay-2013-3", topicText: "GDP along with GDH would be the right indices for judging well-being", category: "Economy", source: "pyq", year: 2013 },
  { id: "essay-2013-4", topicText: "Science and technology is the panacea for growth and security", category: "Science and Technology", source: "pyq", year: 2013 },
  { id: "essay-2014-1", topicText: "With greater power comes greater responsibility", category: "Philosophy & Values", source: "pyq", year: 2014 },
  { id: "essay-2014-2", topicText: "Is the growing level of competition good for the youth?", category: "Society and Social Justice", source: "pyq", year: 2014 },
  { id: "essay-2014-3", topicText: "Are standardized tests good measure of academic ability?", category: "Philosophy & Values", source: "pyq", year: 2014 },
  { id: "essay-2014-4", topicText: "Words are sharper than the two-edged sword", category: "Philosophy & Values", source: "pyq", year: 2014 },
  { id: "essay-2014-5", topicText: "Policy paralysis or paralysis of implementation slowed growth?", category: "Economy", source: "pyq", year: 2014 },
  { id: "essay-2014-6", topicText: "Is sting operation an invasion on privacy?", category: "Philosophy & Values", source: "pyq", year: 2014 },
  { id: "essay-2014-7", topicText: "Fifty Golds in Olympics: Can this be reality for India?", category: "Philosophy & Values", source: "pyq", year: 2014 },
  { id: "essay-2014-8", topicText: "Tourism: Can this be the next big thing for India?", category: "Philosophy & Values", source: "pyq", year: 2014 },
  { id: "essay-2015-1", topicText: "Lending hands is better than giving a dole", category: "Philosophy & Values", source: "pyq", year: 2015 },
  { id: "essay-2015-2", topicText: "Quick but steady wins the race", category: "Philosophy & Values", source: "pyq", year: 2015 },
  { id: "essay-2015-3", topicText: "Character of institution reflected in its leader", category: "Philosophy & Values", source: "pyq", year: 2015 },
  { id: "essay-2015-4", topicText: "Education without values, as useful as it is, seems rather to make a man more clever devil", category: "Education", source: "pyq", year: 2015 },
  { id: "essay-2015-5", topicText: "Technology cannot replace manpower", category: "Science and Technology", source: "pyq", year: 2015 },
  { id: "essay-2015-6", topicText: "Crisis faced in India — moral or economic?", category: "Economy", source: "pyq", year: 2015 },
  { id: "essay-2015-7", topicText: "Dreams which should not let India sleep", category: "Philosophy & Values", source: "pyq", year: 2015 },
  { id: "essay-2015-8", topicText: "Can capitalism bring inclusive growth?", category: "Economy", source: "pyq", year: 2015 },
  { id: "essay-2016-1", topicText: "If development is not engendered, it is endangered", category: "Women & Gender", source: "pyq", year: 2016 },
  { id: "essay-2016-2", topicText: "Need brings greed, if greed increases it spoils breed", category: "Philosophy & Values", source: "pyq", year: 2016 },
  { id: "essay-2016-3", topicText: "Water disputes between states in federal India", category: "Polity and Governance", source: "pyq", year: 2016 },
  { id: "essay-2016-4", topicText: "Innovation is the key determinant of economic growth and social welfare", category: "Economy", source: "pyq", year: 2016 },
  { id: "essay-2016-5", topicText: "Cooperative federalism: Myth or reality?", category: "Polity and Governance", source: "pyq", year: 2016 },
  { id: "essay-2016-6", topicText: "Cyberspace and internet: Blessing or curse to human civilization?", category: "Science and Technology", source: "pyq", year: 2016 },
  { id: "essay-2016-7", topicText: "Near jobless growth in India: An anomaly or outcome of reforms?", category: "Economy", source: "pyq", year: 2016 },
  { id: "essay-2016-8", topicText: "Digital economy: A leveller or source of economic inequality?", category: "Science and Technology", source: "pyq", year: 2016 },
  { id: "essay-2017-1", topicText: "Farming has lost the ability to be subsistence source for majority", category: "Philosophy & Values", source: "pyq", year: 2017 },
  { id: "essay-2017-2", topicText: "Impact of new economic measures on fiscal ties between union and states", category: "Economy", source: "pyq", year: 2017 },
  { id: "essay-2017-3", topicText: "Destiny of a nation is shaped in its classrooms", category: "Education", source: "pyq", year: 2017 },
  { id: "essay-2017-4", topicText: "Has Non-Alignment Movement lost relevance in multipolar world?", category: "International Relations", source: "pyq", year: 2017 },
  { id: "essay-2017-5", topicText: "Joy is the simplest form of gratitude", category: "Philosophy & Values", source: "pyq", year: 2017 },
  { id: "essay-2017-6", topicText: "Fulfillment of 'new woman' in India is a myth", category: "Women & Gender", source: "pyq", year: 2017 },
  { id: "essay-2017-7", topicText: "We may brave human laws but cannot resist natural laws", category: "Environment", source: "pyq", year: 2017 },
  { id: "essay-2017-8", topicText: "Social media is inherently a selfish medium", category: "Culture and Media", source: "pyq", year: 2017 },
  { id: "essay-2018-1", topicText: "Alternative technologies for climate change resilient India", category: "Environment", source: "pyq", year: 2018 },
  { id: "essay-2018-2", topicText: "A good life is one inspired by love and guided by knowledge", category: "Philosophy & Values", source: "pyq", year: 2018 },
  { id: "essay-2018-3", topicText: "Poverty anywhere is a threat to prosperity everywhere", category: "Economy", source: "pyq", year: 2018 },
  { id: "essay-2018-4", topicText: "Management of Indian border disputes — a complex task", category: "International Relations", source: "pyq", year: 2018 },
  { id: "essay-2018-5", topicText: "Customary morality cannot be a guide to modern life", category: "Philosophy & Values", source: "pyq", year: 2018 },
  { id: "essay-2018-6", topicText: "'The past' is a permanent dimension of human consciousness", category: "Philosophy & Values", source: "pyq", year: 2018 },
  { id: "essay-2018-7", topicText: "A people that values privileges above principles loses both", category: "Philosophy & Values", source: "pyq", year: 2018 },
  { id: "essay-2018-8", topicText: "Reality does not conform to the ideal, but confirms it", category: "Philosophy & Values", source: "pyq", year: 2018 },
  { id: "essay-2019-1", topicText: "Wisdom finds truth", category: "Philosophy & Values", source: "pyq", year: 2019 },
  { id: "essay-2019-2", topicText: "Values are not what humanity is, but what humanity ought to be", category: "Philosophy & Values", source: "pyq", year: 2019 },
  { id: "essay-2019-3", topicText: "Best for an individual is not necessarily best for society", category: "Society and Social Justice", source: "pyq", year: 2019 },
  { id: "essay-2019-4", topicText: "Courage to accept and dedication to improve are two keys to success", category: "Philosophy & Values", source: "pyq", year: 2019 },
  { id: "essay-2019-5", topicText: "South Asian societies woven around plural cultures and identities", category: "Culture and Media", source: "pyq", year: 2019 },
  { id: "essay-2019-6", topicText: "Neglect of primary health care and education reasons for backwardness", category: "Education", source: "pyq", year: 2019 },
  { id: "essay-2019-7", topicText: "Biased media is a real threat to Indian democracy", category: "Culture and Media", source: "pyq", year: 2019 },
  { id: "essay-2019-8", topicText: "Rise of AI: jobless future or better opportunities through reskilling?", category: "Philosophy & Values", source: "pyq", year: 2019 },
  { id: "essay-2020-1", topicText: "Life is a long journey between human being and being humane", category: "Philosophy & Values", source: "pyq", year: 2020 },
  { id: "essay-2020-2", topicText: "Mindful manifesto is the catalyst to a tranquil self", category: "Philosophy & Values", source: "pyq", year: 2020 },
  { id: "essay-2020-3", topicText: "Ships do not sink because of water around them; they sink because of water inside", category: "Philosophy & Values", source: "pyq", year: 2020 },
  { id: "essay-2020-4", topicText: "Simplicity is the ultimate sophistication", category: "Philosophy & Values", source: "pyq", year: 2020 },
  { id: "essay-2020-5", topicText: "Culture is what we are, civilization is what we have", category: "Culture and Media", source: "pyq", year: 2020 },
  { id: "essay-2020-6", topicText: "No social justice without economic prosperity; prosperity without justice is meaningless", category: "Economy", source: "pyq", year: 2020 },
  { id: "essay-2020-7", topicText: "Patriarchy is the least noticed yet most significant structure of inequality", category: "Women & Gender", source: "pyq", year: 2020 },
  { id: "essay-2020-8", topicText: "Technology as the silent factor in international relations", category: "Science and Technology", source: "pyq", year: 2020 },
  { id: "essay-2021-1", topicText: "The process of self-discovery has now been technologically outsourced", category: "Philosophy & Values", source: "pyq", year: 2021 },
  { id: "essay-2021-2", topicText: "Your perception of me is a reflection of you; my reaction to you is awareness of me", category: "Philosophy & Values", source: "pyq", year: 2021 },
  { id: "essay-2021-3", topicText: "Philosophy of wantlessness is Utopian, while materialism is a chimera", category: "Philosophy & Values", source: "pyq", year: 2021 },
  { id: "essay-2021-4", topicText: "The real is rational and the rational is real", category: "Philosophy & Values", source: "pyq", year: 2021 },
  { id: "essay-2021-5", topicText: "Hand that rocks the cradle rules the world", category: "Women & Gender", source: "pyq", year: 2021 },
  { id: "essay-2021-6", topicText: "What is research, but a blind date with knowledge?", category: "Philosophy & Values", source: "pyq", year: 2021 },
  { id: "essay-2021-7", topicText: "History repeats itself, first as a tragedy, second as a farce", category: "Philosophy & Values", source: "pyq", year: 2021 },
  { id: "essay-2021-8", topicText: "There are better practices to \"best practices\"", category: "Philosophy & Values", source: "pyq", year: 2021 },
  { id: "essay-2022-1", topicText: "Forests are the best case studies for economic excellence", category: "Environment", source: "pyq", year: 2022 },
  { id: "essay-2022-2", topicText: "Poets are the unacknowledged legislators of the world", category: "Philosophy & Values", source: "pyq", year: 2022 },
  { id: "essay-2022-3", topicText: "History is a series of victories won by scientific over romantic man", category: "Philosophy & Values", source: "pyq", year: 2022 },
  { id: "essay-2022-4", topicText: "A ship in the harbour is safe but that is not what a ship is for", category: "Philosophy & Values", source: "pyq", year: 2022 },
  { id: "essay-2022-5", topicText: "The time to repair the roof is when the sun is shining", category: "Philosophy & Values", source: "pyq", year: 2022 },
  { id: "essay-2022-6", topicText: "You cannot step twice in the same river", category: "Philosophy & Values", source: "pyq", year: 2022 },
  { id: "essay-2022-7", topicText: "Smile is the chosen vehicle for all ambiguities", category: "Philosophy & Values", source: "pyq", year: 2022 },
  { id: "essay-2022-8", topicText: "Just because you have a choice does not mean any has to be right", category: "Philosophy & Values", source: "pyq", year: 2022 },
  { id: "essay-2023-1", topicText: "Thinking is like a game; it does not begin unless there is an opposite team", category: "Philosophy & Values", source: "pyq", year: 2023 },
  { id: "essay-2023-2", topicText: "Visionary decision-making happens at intersection of intuition and logic", category: "Philosophy & Values", source: "pyq", year: 2023 },
  { id: "essay-2023-3", topicText: "Not all who wander are lost", category: "Philosophy & Values", source: "pyq", year: 2023 },
  { id: "essay-2023-4", topicText: "Inspiration for creativity springs from effort to look for the magical in mundane", category: "Philosophy & Values", source: "pyq", year: 2023 },
  { id: "essay-2023-5", topicText: "Girls are weighed down by restrictions, boys with demands", category: "Women & Gender", source: "pyq", year: 2023 },
  { id: "essay-2023-6", topicText: "Mathematics is the music of reason", category: "Philosophy & Values", source: "pyq", year: 2023 },
  { id: "essay-2023-7", topicText: "A society that has more justice is a society that needs less charity", category: "Society and Social Justice", source: "pyq", year: 2023 },
  { id: "essay-2023-8", topicText: "Education is what remains after one has forgotten school learning", category: "Education", source: "pyq", year: 2023 },
  { id: "essay-2024-1", topicText: "Forests precede civilizations and deserts follow them", category: "Environment", source: "pyq", year: 2024 },
  { id: "essay-2024-2", topicText: "The empires of the future will be the empires of the mind", category: "Philosophy & Values", source: "pyq", year: 2024 },
  { id: "essay-2024-3", topicText: "There is no path to happiness; Happiness is the path", category: "Philosophy & Values", source: "pyq", year: 2024 },
  { id: "essay-2024-4", topicText: "The doubter is a true man of Science", category: "Science and Technology", source: "pyq", year: 2024 },
  { id: "essay-2024-5", topicText: "Social media triggering 'Fear of Missing Out' among youth", category: "Culture and Media", source: "pyq", year: 2024 },
  { id: "essay-2024-6", topicText: "Nearly all men can stand adversity, but to test character, give him power", category: "Philosophy & Values", source: "pyq", year: 2024 },
  { id: "essay-2024-7", topicText: "All ideas having large consequences are always simple", category: "Philosophy & Values", source: "pyq", year: 2024 },
  { id: "essay-2024-8", topicText: "The cost of being wrong is less than the cost of doing nothing", category: "Philosophy & Values", source: "pyq", year: 2024 },
  { id: "essay-2025-1", topicText: "Truth knows no color", category: "Philosophy & Values", source: "pyq", year: 2025 },
  { id: "essay-2025-2", topicText: "The supreme art of war is to subdue enemy without fighting", category: "Philosophy & Values", source: "pyq", year: 2025 },
  { id: "essay-2025-3", topicText: "Thought finds a world and creates one also", category: "Philosophy & Values", source: "pyq", year: 2025 },
  { id: "essay-2025-4", topicText: "Best lessons are learnt through bitter experiences", category: "Philosophy & Values", source: "pyq", year: 2025 },
  { id: "essay-2025-5", topicText: "Muddy water is best cleared by leaving it alone", category: "Philosophy & Values", source: "pyq", year: 2025 },
  { id: "essay-2025-6", topicText: "The years teach much which the days never know", category: "Philosophy & Values", source: "pyq", year: 2025 },
  { id: "essay-2025-7", topicText: "It is best to see life as a journey, not as a destination", category: "Philosophy & Values", source: "pyq", year: 2025 },
  { id: "essay-2025-8", topicText: "Contentment is natural wealth; luxury is artificial poverty", category: "Economy", source: "pyq", year: 2025 },
  { id: "essay-guide-philosophy-values-1", topicText: "Everything comes to him, who hustles while he waits", category: "Philosophy & Values", source: "guidance", year: null },
  { id: "essay-guide-philosophy-values-2", topicText: "We are always blind as we want to be", category: "Philosophy & Values", source: "guidance", year: null },
  { id: "essay-guide-philosophy-values-3", topicText: "A disciplined mind brings happiness", category: "Philosophy & Values", source: "guidance", year: null },
  { id: "essay-guide-philosophy-values-4", topicText: "The price of Greatness is Responsibility", category: "Philosophy & Values", source: "guidance", year: null },
  { id: "essay-guide-philosophy-values-5", topicText: "People would rather Believe than Know", category: "Philosophy & Values", source: "guidance", year: null },
  { id: "essay-guide-philosophy-values-6", topicText: "Mind - A beautiful Servant? Or a dangerous Master?", category: "Philosophy & Values", source: "guidance", year: null },
  { id: "essay-guide-philosophy-values-7", topicText: "What you think, you become – The power of thoughts", category: "Philosophy & Values", source: "guidance", year: null },
  { id: "essay-guide-philosophy-values-8", topicText: "Not everything that is faced can be changed, but nothing can be changed until it is faced", category: "Philosophy & Values", source: "guidance", year: null },
  { id: "essay-guide-philosophy-values-9", topicText: "The journey is more important than the destination", category: "Philosophy & Values", source: "guidance", year: null },
  { id: "essay-guide-philosophy-values-10", topicText: "Discipline is the bridge between goals and accomplishment", category: "Philosophy & Values", source: "guidance", year: null },
  { id: "essay-guide-philosophy-values-11", topicText: "Life is a series of natural and spontaneous changes – adapt to grow", category: "Philosophy & Values", source: "guidance", year: null },
  { id: "essay-guide-philosophy-values-12", topicText: "Clarity emerges after doubt, not before it", category: "Philosophy & Values", source: "guidance", year: null },
  { id: "essay-guide-philosophy-values-13", topicText: "What you sow, so shall you reap", category: "Philosophy & Values", source: "guidance", year: null },
  { id: "essay-guide-philosophy-values-14", topicText: "True greatness is not measured by the absence of failure, but by the ability to rise after falling", category: "Philosophy & Values", source: "guidance", year: null },
  { id: "essay-guide-philosophy-values-15", topicText: "We do not see things as they are; we see them as we are", category: "Philosophy & Values", source: "guidance", year: null },
  { id: "essay-guide-philosophy-values-16", topicText: "Every age believes it is unique; every age is mistaken", category: "Philosophy & Values", source: "guidance", year: null },
  { id: "essay-guide-philosophy-values-17", topicText: "Silence is the loudest answer to noise", category: "Philosophy & Values", source: "guidance", year: null },
  { id: "essay-guide-philosophy-values-18", topicText: "The map is not the territory", category: "Philosophy & Values", source: "guidance", year: null },
  { id: "essay-guide-philosophy-values-19", topicText: "To know what you know and what you do not know — that is true knowledge", category: "Philosophy & Values", source: "guidance", year: null },
  { id: "essay-guide-philosophy-values-20", topicText: "Freedom is the discipline of choosing what to refuse", category: "Philosophy & Values", source: "guidance", year: null },
  { id: "essay-guide-philosophy-values-21", topicText: "Memory is the architect of identity; forgetting is its sculptor", category: "Philosophy & Values", source: "guidance", year: null },
  { id: "essay-guide-philosophy-values-22", topicText: "Hope is not the absence of darkness; it is the courage to begin again", category: "Philosophy & Values", source: "guidance", year: null },
  { id: "essay-guide-philosophy-values-23", topicText: "The shortest path between two truths often runs through a paradox", category: "Philosophy & Values", source: "guidance", year: null },
  { id: "essay-guide-philosophy-values-24", topicText: "Wisdom is knowing what to overlook", category: "Philosophy & Values", source: "guidance", year: null },
  { id: "essay-guide-philosophy-values-25", topicText: "A mind without purpose will wander in dark places", category: "Philosophy & Values", source: "guidance", year: null },
  { id: "essay-guide-philosophy-values-26", topicText: "Patience is a form of action, not the absence of it", category: "Philosophy & Values", source: "guidance", year: null },
  { id: "essay-guide-philosophy-values-27", topicText: "Solitude is where we meet ourselves", category: "Philosophy & Values", source: "guidance", year: null },
  { id: "essay-guide-philosophy-values-28", topicText: "The limits of our language are the limits of our world", category: "Philosophy & Values", source: "guidance", year: null },
  { id: "essay-guide-philosophy-values-29", topicText: "We are shaped not by what we gain but by what we are willing to lose", category: "Philosophy & Values", source: "guidance", year: null },
  { id: "essay-guide-philosophy-values-30", topicText: "To question well is to half-answer", category: "Philosophy & Values", source: "guidance", year: null },
  { id: "essay-guide-philosophy-values-31", topicText: "Boredom is the gateway to imagination", category: "Philosophy & Values", source: "guidance", year: null },
  { id: "essay-guide-philosophy-values-32", topicText: "Beauty is not what is rare; it is what is noticed", category: "Philosophy & Values", source: "guidance", year: null },
  { id: "essay-guide-philosophy-values-33", topicText: "A truth is not less true for being unwelcome", category: "Philosophy & Values", source: "guidance", year: null },
  { id: "essay-guide-philosophy-values-34", topicText: "The loudest paradox of progress is that we are dying of our remedies", category: "Philosophy & Values", source: "guidance", year: null },
  { id: "essay-guide-philosophy-values-35", topicText: "Crisis does not build character; it merely strips away the illusions that concealed its absence", category: "Philosophy & Values", source: "guidance", year: null },
  { id: "essay-guide-philosophy-values-36", topicText: "When data replaces thought and algorithms replace empathy, society exchanges its wisdom for mere efficiency", category: "Philosophy & Values", source: "guidance", year: null },
  { id: "essay-guide-philosophy-values-37", topicText: "True empowerment is not when the marginalised gain the power to dominate, but when they dismantle the architecture of domination itself", category: "Philosophy & Values", source: "guidance", year: null },
  { id: "essay-guide-philosophy-values-38", topicText: "Leadership is an action, not a position; a responsibility to serve, not a privilege to rule", category: "Philosophy & Values", source: "guidance", year: null },
  { id: "essay-guide-philosophy-values-39", topicText: "Prejudice sees what it pleases; reason sees what is actually there", category: "Philosophy & Values", source: "guidance", year: null },
  { id: "essay-guide-philosophy-values-40", topicText: "The river of time does not erode anchor points; it exposes those that were built on sand", category: "Philosophy & Values", source: "guidance", year: null },
  { id: "essay-guide-philosophy-values-41", topicText: "The hunger of accumulation is a modern mirage; true asset-building is the reduction of unnecessary burdens", category: "Philosophy & Values", source: "guidance", year: null },
  { id: "essay-guide-philosophy-values-42", topicText: "Power without purpose is a rudderless ship in a turbulent sea", category: "Philosophy & Values", source: "guidance", year: null },
  { id: "essay-guide-philosophy-values-43", topicText: "Exploration is the manifestation of human courage, but it carries the heavy burden of the unknown", category: "Philosophy & Values", source: "guidance", year: null },
  { id: "essay-guide-philosophy-values-44", topicText: "Memory is a Burden, Oblivion is a Strategy", category: "Philosophy & Values", source: "guidance", year: null },
  { id: "essay-guide-philosophy-values-45", topicText: "Truth is the First Casualty of Convenience, but Reality is the Final Arbiter", category: "Philosophy & Values", source: "guidance", year: null },
  { id: "essay-guide-philosophy-values-46", topicText: "Silence is often the loudest form of protest in a noisy democracy", category: "Philosophy & Values", source: "guidance", year: null },
  { id: "essay-guide-philosophy-values-47", topicText: "In the quest for 'more,' we have forgotten the virtue of 'enough'", category: "Philosophy & Values", source: "guidance", year: null },
  { id: "essay-guide-philosophy-values-48", topicText: "Greatness is self-seeded, not crowd-sourced", category: "Philosophy & Values", source: "guidance", year: null },
  { id: "essay-guide-philosophy-values-49", topicText: "The oak fought the wind and was broken; the willow bent when it must and survived", category: "Philosophy & Values", source: "guidance", year: null },
  { id: "essay-guide-philosophy-values-50", topicText: "Attitude Shapes Tomorrow's Human Potential", category: "Philosophy & Values", source: "guidance", year: null },
  { id: "essay-guide-philosophy-values-51", topicText: "A meaningful life rests on love and knowledge", category: "Philosophy & Values", source: "guidance", year: null },
  { id: "essay-guide-philosophy-values-52", topicText: "The true cost of convenience is often paid invisibly", category: "Philosophy & Values", source: "guidance", year: null },
  { id: "essay-guide-philosophy-values-53", topicText: "Human progress is measured less by control over nature and more by responsibility toward it", category: "Philosophy & Values", source: "guidance", year: null },
  { id: "essay-guide-philosophy-values-54", topicText: "Development without justice is merely a different form of exploitation", category: "Philosophy & Values", source: "guidance", year: null },
  { id: "essay-guide-philosophy-values-55", topicText: "The doubter is the true man of science, but the believer is the true man of action", category: "Philosophy & Values", source: "guidance", year: null },
  { id: "essay-guide-philosophy-values-56", topicText: "Silence can preserve peace, but it can also perpetuate injustice", category: "Philosophy & Values", source: "guidance", year: null },
  { id: "essay-guide-philosophy-values-57", topicText: "The pursuit of certainty often limits the scope of progress", category: "Philosophy & Values", source: "guidance", year: null },
  { id: "essay-guide-philosophy-values-58", topicText: "Power without legitimacy is fragile, and legitimacy without accountability is dangerous", category: "Philosophy & Values", source: "guidance", year: null },
  { id: "essay-guide-philosophy-values-59", topicText: "Comfort often becomes the greatest obstacle to change", category: "Philosophy & Values", source: "guidance", year: null },
  { id: "essay-guide-philosophy-values-60", topicText: "The abundance of options often conceals the poverty of purpose", category: "Philosophy & Values", source: "guidance", year: null },
  { id: "essay-guide-philosophy-values-61", topicText: "The future is shaped less by prediction than by preparation", category: "Philosophy & Values", source: "guidance", year: null },
  { id: "essay-guide-philosophy-values-62", topicText: "The pursuit of comfort often comes at the cost of resilience", category: "Philosophy & Values", source: "guidance", year: null },
  { id: "essay-guide-philosophy-values-63", topicText: "Diversity strengthens societies when guided by mutual respect", category: "Philosophy & Values", source: "guidance", year: null },
  { id: "essay-guide-philosophy-values-64", topicText: "We do not inherit the Earth from our ancestors, we borrow it from future generations", category: "Philosophy & Values", source: "guidance", year: null },
  { id: "essay-guide-philosophy-values-65", topicText: "Not everything that is technologically possible is ethically desirable", category: "Philosophy & Values", source: "guidance", year: null },
  { id: "essay-guide-philosophy-values-66", topicText: "The erosion of trust is the beginning of institutional decline", category: "Philosophy & Values", source: "guidance", year: null },
  { id: "essay-guide-philosophy-values-67", topicText: "The pursuit of success often overlooks the value of significance", category: "Philosophy & Values", source: "guidance", year: null },
  { id: "essay-guide-philosophy-values-68", topicText: "The quality of a society is reflected not in its achievements, but in its choices", category: "Philosophy & Values", source: "guidance", year: null },
  { id: "essay-guide-philosophy-values-69", topicText: "Civilisations endure when wisdom keeps pace with innovation", category: "Philosophy & Values", source: "guidance", year: null },
  { id: "essay-guide-philosophy-values-70", topicText: "A civilisation survives not by strength alone, but by self-correction", category: "Philosophy & Values", source: "guidance", year: null },
  { id: "essay-guide-philosophy-values-71", topicText: "Order without justice is merely organised injustice", category: "Philosophy & Values", source: "guidance", year: null },
  { id: "essay-guide-philosophy-values-72", topicText: "Poverty is the parent of revolution and crime", category: "Philosophy & Values", source: "guidance", year: null },
  { id: "essay-guide-philosophy-values-73", topicText: "He who has a 'why' to live for can bear almost any 'how'", category: "Philosophy & Values", source: "guidance", year: null },
  { id: "essay-guide-philosophy-values-74", topicText: "The true test of freedom lies in the ability to self-regulate", category: "Philosophy & Values", source: "guidance", year: null },
  { id: "essay-guide-philosophy-values-75", topicText: "You can't cross the sea merely by standing and staring at the water", category: "Philosophy & Values", source: "guidance", year: null },
  { id: "essay-guide-philosophy-values-76", topicText: "Capabilities create opportunities, but character determines outcomes", category: "Philosophy & Values", source: "guidance", year: null },
  { id: "essay-guide-philosophy-values-77", topicText: "In the era of instant reactions, thoughtful restraint is revolutionary", category: "Philosophy & Values", source: "guidance", year: null },
  { id: "essay-guide-philosophy-values-78", topicText: "Efficiency may optimize systems, but values sustain societies", category: "Philosophy & Values", source: "guidance", year: null },
  { id: "essay-guide-philosophy-values-79", topicText: "Freedom without ethical restraint becomes another form of inequality", category: "Philosophy & Values", source: "guidance", year: null },
  { id: "essay-guide-philosophy-values-80", topicText: "Institutions endure when values outlive individuals", category: "Philosophy & Values", source: "guidance", year: null },
  { id: "essay-guide-philosophy-values-81", topicText: "In a connected world, empathy is the new currency of leadership", category: "Philosophy & Values", source: "guidance", year: null },
  { id: "essay-guide-philosophy-values-82", topicText: "Nature protects those who protect it", category: "Philosophy & Values", source: "guidance", year: null },
  { id: "essay-guide-philosophy-values-83", topicText: "Development is not merely the expansion of choices, but the cultivation of conscience", category: "Philosophy & Values", source: "guidance", year: null },
  { id: "essay-guide-philosophy-values-84", topicText: "Technology empowers, but institutions humanise governance", category: "Philosophy & Values", source: "guidance", year: null },
  { id: "essay-guide-philosophy-values-85", topicText: "Progress without purpose is movement without meaning", category: "Philosophy & Values", source: "guidance", year: null },
  { id: "essay-guide-philosophy-values-86", topicText: "Technology can amplify human potential, but it cannot replace human judgment", category: "Philosophy & Values", source: "guidance", year: null },
  { id: "essay-guide-philosophy-values-87", topicText: "Cultural roots give societies resilience in times of rapid change", category: "Philosophy & Values", source: "guidance", year: null },
  { id: "essay-guide-philosophy-values-88", topicText: "A rising tide lifts all boats", category: "Philosophy & Values", source: "guidance", year: null },
  { id: "essay-guide-philosophy-values-89", topicText: "Education is not the learning of facts. It's rather the training of the mind to think", category: "Philosophy & Values", source: "guidance", year: null },
  { id: "essay-guide-philosophy-values-90", topicText: "Popular will may shape law, but it cannot be the foundation of justice", category: "Philosophy & Values", source: "guidance", year: null },
  { id: "essay-guide-philosophy-values-91", topicText: "Integrity begins where convenience ends", category: "Philosophy & Values", source: "guidance", year: null },
  { id: "essay-guide-philosophy-values-92", topicText: "In an age of increasing efficiency, humanity's greatest need is compassion, not perfection", category: "Philosophy & Values", source: "guidance", year: null },
  { id: "essay-guide-philosophy-values-93", topicText: "Justice must be rooted in principles, not in public opinion", category: "Philosophy & Values", source: "guidance", year: null },
  { id: "essay-guide-philosophy-values-94", topicText: "The future influences the present just as much as the past", category: "Philosophy & Values", source: "guidance", year: null },
  { id: "essay-guide-philosophy-values-95", topicText: "Destiny is inherited. Education is the argument against inheritance", category: "Philosophy & Values", source: "guidance", year: null },
  { id: "essay-guide-philosophy-values-96", topicText: "Art is the conscience of civilization", category: "Philosophy & Values", source: "guidance", year: null },
  { id: "essay-guide-philosophy-values-97", topicText: "No one is safe until everyone is safe", category: "Philosophy & Values", source: "guidance", year: null },
  { id: "essay-guide-philosophy-values-98", topicText: "Reason teaches us how to think. Suffering teaches us what truly matters", category: "Philosophy & Values", source: "guidance", year: null },
  { id: "essay-guide-philosophy-values-99", topicText: "Devotion to Truth is the sole justification for our existence", category: "Philosophy & Values", source: "guidance", year: null },
  { id: "essay-guide-philosophy-values-100", topicText: "Men build too many walls and not enough bridges", category: "Philosophy & Values", source: "guidance", year: null },
  { id: "essay-guide-philosophy-values-101", topicText: "No act of kindness, no matter how small, is ever wasted", category: "Philosophy & Values", source: "guidance", year: null },
  { id: "essay-guide-philosophy-values-102", topicText: "The purpose of life is to be defeated by greater and greater things", category: "Philosophy & Values", source: "guidance", year: null },
  { id: "essay-guide-philosophy-values-103", topicText: "Poetry is what happens when nothing else can", category: "Philosophy & Values", source: "guidance", year: null },
  { id: "essay-guide-philosophy-values-104", topicText: "Who looks outside, dreams; who looks inside, awakes", category: "Philosophy & Values", source: "guidance", year: null },
  { id: "essay-guide-philosophy-values-105", topicText: "Technology can empower women, but only society can ensure dignity", category: "Philosophy & Values", source: "guidance", year: null },
  { id: "essay-guide-philosophy-values-106", topicText: "Nature does not hurry, yet everything is accomplished", category: "Philosophy & Values", source: "guidance", year: null },
  { id: "essay-guide-philosophy-values-107", topicText: "The heart never takes the place of the head: but it can, and should, obey it", category: "Philosophy & Values", source: "guidance", year: null },
  { id: "essay-guide-philosophy-values-108", topicText: "Generosity is giving more than you can, and pride is taking less than you need", category: "Philosophy & Values", source: "guidance", year: null },
  { id: "essay-guide-philosophy-values-109", topicText: "The world is a book, and those who do not travel read only one page", category: "Philosophy & Values", source: "guidance", year: null },
  { id: "essay-guide-philosophy-values-110", topicText: "Standardization in education risks standardizing minds", category: "Philosophy & Values", source: "guidance", year: null },
  { id: "essay-guide-philosophy-values-111", topicText: "He who cannot be a good follower cannot be a good leader", category: "Philosophy & Values", source: "guidance", year: null },
  { id: "essay-guide-philosophy-values-112", topicText: "When life turns dark, some think they are buried, others believe they are planted", category: "Philosophy & Values", source: "guidance", year: null },
  { id: "essay-guide-philosophy-values-113", topicText: "Dull minds are never either intuitive or mathematical", category: "Philosophy & Values", source: "guidance", year: null },
  { id: "essay-guide-philosophy-values-114", topicText: "Objectivity is the summation of subjectivity", category: "Philosophy & Values", source: "guidance", year: null },
  { id: "essay-guide-philosophy-values-115", topicText: "Ideals are peaceful. History is violent", category: "Philosophy & Values", source: "guidance", year: null },
  { id: "essay-guide-philosophy-values-116", topicText: "Look back over the past, with its changing empires that rose and fell, and you can foresee the future too", category: "Philosophy & Values", source: "guidance", year: null },
  { id: "essay-guide-philosophy-values-117", topicText: "Cultivation of mind should be the ultimate aim of human existence", category: "Philosophy & Values", source: "guidance", year: null },
  { id: "essay-guide-philosophy-values-118", topicText: "When is violence justified — and what does it cost the human soul?", category: "Philosophy & Values", source: "guidance", year: null },
  { id: "essay-guide-philosophy-values-119", topicText: "When you throw mud, you lose ground", category: "Philosophy & Values", source: "guidance", year: null },
  { id: "essay-guide-philosophy-values-120", topicText: "Roots of all miseries lie in ignorance about non-permanence of life", category: "Philosophy & Values", source: "guidance", year: null },
  { id: "essay-guide-philosophy-values-121", topicText: "Kindness is the language that the deaf can hear and the blind can see", category: "Philosophy & Values", source: "guidance", year: null },
  { id: "essay-guide-philosophy-values-122", topicText: "Life can only be understood backwards; but it must be lived forwards", category: "Philosophy & Values", source: "guidance", year: null },
  { id: "essay-guide-philosophy-values-123", topicText: "The most obvious, important realities are often the ones that are hardest to see and talk about", category: "Philosophy & Values", source: "guidance", year: null },
  { id: "essay-guide-philosophy-values-124", topicText: "What you seek is seeking you", category: "Philosophy & Values", source: "guidance", year: null },
  { id: "essay-guide-philosophy-values-125", topicText: "It's easy enough to preach morality on a full belly", category: "Philosophy & Values", source: "guidance", year: null },
  { id: "essay-guide-philosophy-values-126", topicText: "A thing is not necessarily true because a man dies for it", category: "Philosophy & Values", source: "guidance", year: null },
  { id: "essay-guide-philosophy-values-127", topicText: "Without deviation from the norm, progress is not possible", category: "Philosophy & Values", source: "guidance", year: null },
  { id: "essay-guide-philosophy-values-128", topicText: "The heart has its reasons, which reason knows nothing of", category: "Philosophy & Values", source: "guidance", year: null },
  { id: "essay-guide-philosophy-values-129", topicText: "We must accept the finite disappointment, but never lose infinite hope", category: "Philosophy & Values", source: "guidance", year: null },
  { id: "essay-guide-philosophy-values-130", topicText: "Nothing gold can stay", category: "Philosophy & Values", source: "guidance", year: null },
  { id: "essay-guide-philosophy-values-131", topicText: "Everything can be taken from a man but one thing: the last of the human freedoms — to choose one's attitude in any given set of circumstances", category: "Philosophy & Values", source: "guidance", year: null },
  { id: "essay-guide-philosophy-values-132", topicText: "Sometimes the most important thing in a whole day is the rest we take between two deep breaths", category: "Philosophy & Values", source: "guidance", year: null },
  { id: "essay-guide-philosophy-values-133", topicText: "Suffering has always been with us; does it force us to ask the right questions?", category: "Philosophy & Values", source: "guidance", year: null },
  { id: "essay-guide-philosophy-values-134", topicText: "The only thing we have to fear is fear itself", category: "Philosophy & Values", source: "guidance", year: null },
  { id: "essay-guide-philosophy-values-135", topicText: "The price good men pay for indifference to public affairs is to be ruled by evil men", category: "Philosophy & Values", source: "guidance", year: null },
  { id: "essay-guide-philosophy-values-136", topicText: "In the age of information, ignorance is a choice", category: "Philosophy & Values", source: "guidance", year: null },
  { id: "essay-guide-philosophy-values-137", topicText: "Stability is an illusion we seek in a world of change", category: "Philosophy & Values", source: "guidance", year: null },
  { id: "essay-guide-philosophy-values-138", topicText: "History doesn't repeat itself, but it often rhymes", category: "Philosophy & Values", source: "guidance", year: null },
  { id: "essay-guide-philosophy-values-139", topicText: "Civilization is the process of setting man free from men", category: "Philosophy & Values", source: "guidance", year: null },
  { id: "essay-guide-philosophy-values-140", topicText: "Between knowing and not knowing lies the wonder of existence", category: "Philosophy & Values", source: "guidance", year: null },
  { id: "essay-guide-philosophy-values-141", topicText: "Responsibility without authority leads to frustration; authority without responsibility leads to tyranny", category: "Philosophy & Values", source: "guidance", year: null },
  { id: "essay-guide-philosophy-values-142", topicText: "When life takes the wind out of your sails, it is to test you at the oars", category: "Philosophy & Values", source: "guidance", year: null },
  { id: "essay-guide-philosophy-values-143", topicText: "Until you make the unconscious conscious, it will direct your life and you will call it fate", category: "Philosophy & Values", source: "guidance", year: null },
  { id: "essay-guide-philosophy-values-144", topicText: "Equality may be a fiction but nonetheless one must accept it as a governing principle", category: "Philosophy & Values", source: "guidance", year: null },
  { id: "essay-guide-philosophy-values-145", topicText: "Individual needs society for survival, society needs individual for progress", category: "Philosophy & Values", source: "guidance", year: null },
  { id: "essay-guide-philosophy-values-146", topicText: "Everything is connected, but the connections are invisible", category: "Philosophy & Values", source: "guidance", year: null },
  { id: "essay-guide-philosophy-values-147", topicText: "The worst thing is not that the world is unfree, but that people have unlearned their liberty", category: "Philosophy & Values", source: "guidance", year: null },
  { id: "essay-guide-philosophy-values-148", topicText: "A great civilization is not conquered from without until it has destroyed itself from within", category: "Philosophy & Values", source: "guidance", year: null },
  { id: "essay-guide-philosophy-values-149", topicText: "Is space exploration justified amidst Earth's struggles?", category: "Philosophy & Values", source: "guidance", year: null },
  { id: "essay-guide-philosophy-values-150", topicText: "Machine Intelligence Is The Last Invention That Humanity Will Ever Need To Make", category: "Philosophy & Values", source: "guidance", year: null },
  { id: "essay-guide-philosophy-values-151", topicText: "Sometimes it takes a natural disaster to reveal a social disaster", category: "Philosophy & Values", source: "guidance", year: null },
  { id: "essay-guide-philosophy-values-152", topicText: "Power concedes nothing without an organised demand", category: "Philosophy & Values", source: "guidance", year: null },
  { id: "essay-guide-philosophy-values-153", topicText: "Science is the storytelling of our time", category: "Philosophy & Values", source: "guidance", year: null },
  { id: "essay-guide-philosophy-values-154", topicText: "The worst form of inequality is to make unequal things equal", category: "Philosophy & Values", source: "guidance", year: null },
  { id: "essay-guide-philosophy-values-155", topicText: "The fear of suffering is the beginning of sin", category: "Philosophy & Values", source: "guidance", year: null },
  { id: "essay-guide-philosophy-values-156", topicText: "Time is a missing person, sending cryptic postcards from the past", category: "Philosophy & Values", source: "guidance", year: null },
  { id: "essay-guide-philosophy-values-157", topicText: "Freedom is the power to choose our own chains", category: "Philosophy & Values", source: "guidance", year: null },
  { id: "essay-guide-philosophy-values-158", topicText: "You talk when you cease to be at peace with your thoughts", category: "Philosophy & Values", source: "guidance", year: null },
  { id: "essay-guide-philosophy-values-159", topicText: "We cannot be mere consumers of good governance, we must be participants", category: "Philosophy & Values", source: "guidance", year: null },
  { id: "essay-guide-philosophy-values-160", topicText: "When Trade Stops, War Comes", category: "Philosophy & Values", source: "guidance", year: null },
  { id: "essay-guide-philosophy-values-161", topicText: "How you do anything is how you do everything", category: "Philosophy & Values", source: "guidance", year: null },
  { id: "essay-guide-philosophy-values-162", topicText: "Wonder is the beginning of wisdom", category: "Philosophy & Values", source: "guidance", year: null },
  { id: "essay-guide-philosophy-values-163", topicText: "The moral arc of the universe bends at the elbow of justice", category: "Philosophy & Values", source: "guidance", year: null },
  { id: "essay-guide-philosophy-values-164", topicText: "The unexamined life is not worth living", category: "Philosophy & Values", source: "guidance", year: null },
  { id: "essay-guide-philosophy-values-165", topicText: "The worst form of injustice is pretended justice", category: "Philosophy & Values", source: "guidance", year: null },
  { id: "essay-guide-philosophy-values-166", topicText: "Science is the poetry of reality", category: "Philosophy & Values", source: "guidance", year: null },
  { id: "essay-guide-philosophy-values-167", topicText: "A Budget Tells Us What We Cannot Afford, But It Doesn't Keep Us from Buying It", category: "Philosophy & Values", source: "guidance", year: null },
  { id: "essay-guide-philosophy-values-168", topicText: "The world is not magic and that is the most magical thing about it", category: "Philosophy & Values", source: "guidance", year: null },
  { id: "essay-guide-philosophy-values-169", topicText: "Art is I; Science is We", category: "Philosophy & Values", source: "guidance", year: null },
  { id: "essay-guide-philosophy-values-170", topicText: "History, in general, only informs us what bad government is", category: "Philosophy & Values", source: "guidance", year: null },
  { id: "essay-guide-philosophy-values-171", topicText: "Wound is the place where light enters you", category: "Philosophy & Values", source: "guidance", year: null },
  { id: "essay-guide-philosophy-values-172", topicText: "What is Religion to One is Superstition To Another", category: "Philosophy & Values", source: "guidance", year: null },
  { id: "essay-guide-philosophy-values-173", topicText: "Gender Is a Spectrum", category: "Philosophy & Values", source: "guidance", year: null },
  { id: "essay-guide-philosophy-values-174", topicText: "Those who were seen dancing were thought to be insane by those who could not hear the music", category: "Philosophy & Values", source: "guidance", year: null },
  { id: "essay-guide-philosophy-values-175", topicText: "Saint Has A Past. Sinner Has A Future", category: "Philosophy & Values", source: "guidance", year: null },
  { id: "essay-guide-philosophy-values-176", topicText: "The worst disease in the world today is corruption and the cure for it is transparency", category: "Philosophy & Values", source: "guidance", year: null },
  { id: "essay-guide-philosophy-values-177", topicText: "Escape Competition Through Authenticity", category: "Philosophy & Values", source: "guidance", year: null },
  { id: "essay-guide-philosophy-values-178", topicText: "Creativity Is Allowing Yourself to Make Mistakes. Art Is Knowing Which Ones to Keep", category: "Philosophy & Values", source: "guidance", year: null },
  { id: "essay-guide-philosophy-values-179", topicText: "In No Man's Land, the only way to survive is to adapt", category: "Philosophy & Values", source: "guidance", year: null },
  { id: "essay-guide-philosophy-values-180", topicText: "Economics is concerned with what emerges, not what anyone intended", category: "Philosophy & Values", source: "guidance", year: null },
  { id: "essay-guide-philosophy-values-181", topicText: "A right is not what someone gives you; it's what no one can take from you", category: "Philosophy & Values", source: "guidance", year: null },
  { id: "essay-guide-philosophy-values-182", topicText: "We come nearest to the great when we are great in humility", category: "Philosophy & Values", source: "guidance", year: null },
  { id: "essay-guide-philosophy-values-183", topicText: "Well done is better than well said", category: "Philosophy & Values", source: "guidance", year: null },
  { id: "essay-guide-philosophy-values-184", topicText: "Consistency is the last refuge of the unimaginative", category: "Philosophy & Values", source: "guidance", year: null },
  { id: "essay-guide-philosophy-values-185", topicText: "A Business That Makes Nothing More Than Money Is Poor Business", category: "Philosophy & Values", source: "guidance", year: null },
  { id: "essay-guide-philosophy-values-186", topicText: "If Voting Really Made a Difference, They Would Not Let Us Do It", category: "Philosophy & Values", source: "guidance", year: null },
  { id: "essay-guide-philosophy-values-187", topicText: "Cinema Is Not A Slice Of Life, But A Piece Of Cake", category: "Philosophy & Values", source: "guidance", year: null },
  { id: "essay-guide-philosophy-values-188", topicText: "Education Can give skill, but a liberal education can give dignity", category: "Philosophy & Values", source: "guidance", year: null },
  { id: "essay-guide-philosophy-values-189", topicText: "Sometimes when you lose your way you find yourself", category: "Philosophy & Values", source: "guidance", year: null },
  { id: "essay-guide-philosophy-values-190", topicText: "Never Let School Interfere With Your Education", category: "Philosophy & Values", source: "guidance", year: null },
  { id: "essay-guide-philosophy-values-191", topicText: "Whoever Controls the Media Controls the Mind", category: "Philosophy & Values", source: "guidance", year: null },
  { id: "essay-guide-philosophy-values-192", topicText: "A certain darkness is needed to see the stars", category: "Philosophy & Values", source: "guidance", year: null },
  { id: "essay-guide-philosophy-values-193", topicText: "Those who cannot remember the past are condemned to repeat it", category: "Philosophy & Values", source: "guidance", year: null },
  { id: "essay-guide-philosophy-values-194", topicText: "Subtle Is Powerful", category: "Philosophy & Values", source: "guidance", year: null },
  { id: "essay-guide-philosophy-values-195", topicText: "The power of community to create health is far greater than any physician, clinic or hospital", category: "Philosophy & Values", source: "guidance", year: null },
  { id: "essay-guide-art-and-culture-1", topicText: "Culture changes with economic development", category: "Art and Culture", source: "guidance", year: null },
  { id: "essay-guide-art-and-culture-2", topicText: "Social reform is a myth if places of worship are open only to all castes and not to all genders", category: "Art and Culture", source: "guidance", year: null },
  { id: "essay-guide-art-and-culture-3", topicText: "Impact of Globalization on Indian Art and Culture", category: "Art and Culture", source: "guidance", year: null },
  { id: "essay-guide-art-and-culture-4", topicText: "Caste System - India's Enduring Curse", category: "Art and Culture", source: "guidance", year: null },
  { id: "essay-guide-art-and-culture-5", topicText: "Godmen - A Threat to Indian Art and Culture?", category: "Art and Culture", source: "guidance", year: null },
  { id: "essay-guide-science-and-technology-1", topicText: "Deglobalisation is good for the world", category: "Science and Technology", source: "guidance", year: null },
  { id: "essay-guide-science-and-technology-2", topicText: "Science is organised Knowledge. Wisdom is Organised life", category: "Science and Technology", source: "guidance", year: null },
  { id: "essay-guide-science-and-technology-3", topicText: "Technology is a Weapon against Poverty", category: "Science and Technology", source: "guidance", year: null },
  { id: "essay-guide-science-and-technology-4", topicText: "Prioritising Education Technology for Global Growth", category: "Science and Technology", source: "guidance", year: null },
  { id: "essay-guide-science-and-technology-5", topicText: "Scientific and Technological Progress cannot be equated with Human Progress", category: "Science and Technology", source: "guidance", year: null },
  { id: "essay-guide-science-and-technology-6", topicText: "Artificial intelligence holds up a mirror to whoever holds it", category: "Science and Technology", source: "guidance", year: null },
  { id: "essay-guide-science-and-technology-7", topicText: "The artist finds beauty; the engineer finds use; both find truth", category: "Science and Technology", source: "guidance", year: null },
  { id: "essay-guide-science-and-technology-8", topicText: "In an age of abundance, the rarest commodity is attention", category: "Science and Technology", source: "guidance", year: null },
  { id: "essay-guide-science-and-technology-9", topicText: "AI will not replace humans; humans who use AI will replace those who do not", category: "Science and Technology", source: "guidance", year: null },
  { id: "essay-guide-science-and-technology-10", topicText: "The algorithm is the new editor-in-chief", category: "Science and Technology", source: "guidance", year: null },
  { id: "essay-guide-science-and-technology-11", topicText: "Genetic editing: the god game we cannot unlearn", category: "Science and Technology", source: "guidance", year: null },
  { id: "essay-guide-science-and-technology-12", topicText: "Space is the last commons; who writes the rules?", category: "Science and Technology", source: "guidance", year: null },
  { id: "essay-guide-science-and-technology-13", topicText: "Privacy is the first casualty of convenience", category: "Science and Technology", source: "guidance", year: null },
  { id: "essay-guide-science-and-technology-14", topicText: "Deepfakes and the death of visual truth", category: "Science and Technology", source: "guidance", year: null },
  { id: "essay-guide-science-and-technology-15", topicText: "Digital India has a rural shadow", category: "Science and Technology", source: "guidance", year: null },
  { id: "essay-guide-science-and-technology-16", topicText: "Technology solves problems it first created", category: "Science and Technology", source: "guidance", year: null },
  { id: "essay-guide-science-and-technology-17", topicText: "Open-source is the language of a freer future", category: "Science and Technology", source: "guidance", year: null },
  { id: "essay-guide-science-and-technology-18", topicText: "When machines speak, will silence become a virtue?", category: "Science and Technology", source: "guidance", year: null },
  { id: "essay-guide-science-and-technology-19", topicText: "Artificial Intelligence: Boon or Bane for humanity?", category: "Science and Technology", source: "guidance", year: null },
  { id: "essay-guide-science-and-technology-20", topicText: "Science and spirituality: Complementary or contradictory?", category: "Science and Technology", source: "guidance", year: null },
  { id: "essay-guide-science-and-technology-21", topicText: "The ethical dilemmas of gene editing", category: "Science and Technology", source: "guidance", year: null },
  { id: "essay-guide-science-and-technology-22", topicText: "Data privacy and the digital citizen", category: "Science and Technology", source: "guidance", year: null },
  { id: "essay-guide-science-and-technology-23", topicText: "Role of science in shaping a better society", category: "Science and Technology", source: "guidance", year: null },
  { id: "essay-guide-science-and-technology-24", topicText: "Digital India: bridging gaps or creating new divides?", category: "Science and Technology", source: "guidance", year: null },
  { id: "essay-guide-education-1", topicText: "Self Education is a lifelong curiosity", category: "Education", source: "guidance", year: null },
  { id: "essay-guide-education-2", topicText: "Education Breeds Peace", category: "Education", source: "guidance", year: null },
  { id: "essay-guide-education-3", topicText: "Education is a progressive discovery of our own ignorance", category: "Education", source: "guidance", year: null },
  { id: "essay-guide-education-4", topicText: "Education must also train one for quick, resolute and effective thinking", category: "Education", source: "guidance", year: null },
  { id: "essay-guide-education-5", topicText: "Schooling is not Education", category: "Education", source: "guidance", year: null },
  { id: "essay-guide-education-6", topicText: "National Education Policy: A transformative step?", category: "Education", source: "guidance", year: null },
  { id: "essay-guide-education-7", topicText: "Role of youth in nation-building", category: "Education", source: "guidance", year: null },
  { id: "essay-guide-education-8", topicText: "India at 100: Role of youth in shaping the future", category: "Education", source: "guidance", year: null },
  { id: "essay-guide-education-9", topicText: "Freedom of speech and responsible expression", category: "Education", source: "guidance", year: null },
  { id: "essay-guide-polity-and-governance-1", topicText: "The Role of Politics in Development", category: "Polity and Governance", source: "guidance", year: null },
  { id: "essay-guide-polity-and-governance-2", topicText: "Should Youth in India Consider Politics as a Career?", category: "Polity and Governance", source: "guidance", year: null },
  { id: "essay-guide-polity-and-governance-3", topicText: "Art, Freedom and Creativity will change society faster than politics", category: "Polity and Governance", source: "guidance", year: null },
  { id: "essay-guide-polity-and-governance-4", topicText: "The politics of Identity is the Politics of the Weak", category: "Polity and Governance", source: "guidance", year: null },
  { id: "essay-guide-polity-and-governance-5", topicText: "People should not be afraid of their Government. The Government should be afraid of its people", category: "Polity and Governance", source: "guidance", year: null },
  { id: "essay-guide-polity-and-governance-6", topicText: "Government Surveillance - Good or Bad?", category: "Polity and Governance", source: "guidance", year: null },
  { id: "essay-guide-polity-and-governance-7", topicText: "Democracy without accountability is a ticking time bomb", category: "Polity and Governance", source: "guidance", year: null },
  { id: "essay-guide-polity-and-governance-8", topicText: "Is Indian democracy evolving or regressing?", category: "Polity and Governance", source: "guidance", year: null },
  { id: "essay-guide-polity-and-governance-9", topicText: "Role of civil services in modern India", category: "Polity and Governance", source: "guidance", year: null },
  { id: "essay-guide-polity-and-governance-10", topicText: "Judicial activism vs Judicial overreach", category: "Polity and Governance", source: "guidance", year: null },
  { id: "essay-guide-polity-and-governance-11", topicText: "Does decentralization strengthen democracy?", category: "Polity and Governance", source: "guidance", year: null },
  { id: "essay-guide-polity-and-governance-12", topicText: "Good governance: A citizen-centric approach", category: "Polity and Governance", source: "guidance", year: null },
  { id: "essay-guide-polity-and-governance-13", topicText: "Transparency and ethics in public administration", category: "Polity and Governance", source: "guidance", year: null },
  { id: "essay-guide-polity-and-governance-14", topicText: "A democracy is measured by the patience of its institutions", category: "Polity and Governance", source: "guidance", year: null },
  { id: "essay-guide-polity-and-governance-15", topicText: "Democracy cannot be delivered; it must be practised", category: "Polity and Governance", source: "guidance", year: null },
  { id: "essay-guide-polity-and-governance-16", topicText: "Federalism is India's most under-appreciated innovation", category: "Polity and Governance", source: "guidance", year: null },
  { id: "essay-guide-polity-and-governance-17", topicText: "The quiet erosion of institutions", category: "Polity and Governance", source: "guidance", year: null },
  { id: "essay-guide-polity-and-governance-18", topicText: "Majoritarianism is a democratic disease, not its cure", category: "Polity and Governance", source: "guidance", year: null },
  { id: "essay-guide-polity-and-governance-19", topicText: "Local government is the unfinished chapter of the Constitution", category: "Polity and Governance", source: "guidance", year: null },
  { id: "essay-guide-polity-and-governance-20", topicText: "Trust is the unwritten preamble of every Constitution", category: "Polity and Governance", source: "guidance", year: null },
  { id: "essay-guide-polity-and-governance-21", topicText: "A bureaucracy too cautious is a state too slow", category: "Polity and Governance", source: "guidance", year: null },
  { id: "essay-guide-polity-and-governance-22", topicText: "Electoral Reforms for Strengthening Democracy: Enhancing transparency", category: "Polity and Governance", source: "guidance", year: null },
  { id: "essay-guide-polity-and-governance-23", topicText: "Judicial Reforms: Improving efficiency and access to justice", category: "Polity and Governance", source: "guidance", year: null },
  { id: "essay-guide-polity-and-governance-24", topicText: "Decentralization and Local Governance: Empowering grassroots institutions", category: "Polity and Governance", source: "guidance", year: null },
  { id: "essay-guide-polity-and-governance-25", topicText: "E-Governance: Transforming public service delivery", category: "Polity and Governance", source: "guidance", year: null },
  { id: "essay-guide-economy-1", topicText: "We don't have to sacrifice a Strong Economy for a Healthy Environment", category: "Economy", source: "guidance", year: null },
  { id: "essay-guide-economy-2", topicText: "India, a $5 trillion Economy - Dream or Reality?", category: "Economy", source: "guidance", year: null },
  { id: "essay-guide-economy-3", topicText: "Digital Economy: A leveller or a source of Economic Inequality?", category: "Economy", source: "guidance", year: null },
  { id: "essay-guide-economy-4", topicText: "Labour Reforms in India and its Role in Economic Growth", category: "Economy", source: "guidance", year: null },
  { id: "essay-guide-economy-5", topicText: "Sustainable Development: Balancing economic growth with environmental conservation", category: "Economy", source: "guidance", year: null },
  { id: "essay-guide-economy-6", topicText: "Digital Economy: Opportunities and challenges in the era of digitization", category: "Economy", source: "guidance", year: null },
  { id: "essay-guide-economy-7", topicText: "Agrarian Crisis: Measures to revitalize the agricultural sector", category: "Economy", source: "guidance", year: null },
  { id: "essay-guide-economy-8", topicText: "Financial Inclusion: Expanding access to financial services in rural areas", category: "Economy", source: "guidance", year: null },
  { id: "essay-guide-economy-9", topicText: "Industry 4.0 and Job Displacement: Preparing for the future of work", category: "Economy", source: "guidance", year: null },
  { id: "essay-guide-economy-10", topicText: "Green Economy: Strategies for sustainable development", category: "Economy", source: "guidance", year: null },
  { id: "essay-guide-economy-11", topicText: "Growth without equity is statistically impressive, socially dangerous", category: "Economy", source: "guidance", year: null },
  { id: "essay-guide-economy-12", topicText: "Demographic dividend is a policy choice, not a gift", category: "Economy", source: "guidance", year: null },
  { id: "essay-guide-economy-13", topicText: "India's middle-income trap: reality or rhetoric?", category: "Economy", source: "guidance", year: null },
  { id: "essay-guide-economy-14", topicText: "Farm to firm: the unfinished migration of Indian labour", category: "Economy", source: "guidance", year: null },
  { id: "essay-guide-economy-15", topicText: "Green growth: oxymoron or imperative?", category: "Economy", source: "guidance", year: null },
  { id: "essay-guide-economy-16", topicText: "Cryptocurrencies and the future of monetary sovereignty", category: "Economy", source: "guidance", year: null },
  { id: "essay-guide-economy-17", topicText: "MSMEs are the forgotten engine of the Indian economy", category: "Economy", source: "guidance", year: null },
  { id: "essay-guide-economy-18", topicText: "Informal work, formal aspirations", category: "Economy", source: "guidance", year: null },
  { id: "essay-guide-economy-19", topicText: "Productivity is the truest form of patriotism", category: "Economy", source: "guidance", year: null },
  { id: "essay-guide-economy-20", topicText: "A national balance sheet that does not value nature lies twice", category: "Economy", source: "guidance", year: null },
  { id: "essay-guide-economy-21", topicText: "Inclusive growth: Myth or reality?", category: "Economy", source: "guidance", year: null },
  { id: "essay-guide-economy-22", topicText: "Unemployment: A ticking time bomb or a demographic dividend?", category: "Economy", source: "guidance", year: null },
  { id: "essay-guide-economy-23", topicText: "India's journey towards a $5 trillion economy", category: "Economy", source: "guidance", year: null },
  { id: "essay-guide-economy-24", topicText: "Globalization vs Atmanirbhar Bharat", category: "Economy", source: "guidance", year: null },
  { id: "essay-guide-economy-25", topicText: "Rural India: Opportunities, challenges and the way forward", category: "Economy", source: "guidance", year: null },
  { id: "essay-guide-economy-26", topicText: "Economic prosperity means little if it is unequal", category: "Economy", source: "guidance", year: null },
  { id: "essay-guide-economy-27", topicText: "Prioritizing social welfare leads to stronger economies", category: "Economy", source: "guidance", year: null },
  { id: "essay-guide-social-issues-1", topicText: "Inclusivity and Plurality are the hallmarks of a Peaceful Society", category: "Social Issues", source: "guidance", year: null },
  { id: "essay-guide-social-issues-2", topicText: "A Gender-sensitive Indian Society is a prerequisite for Women and Child Empowerment", category: "Social Issues", source: "guidance", year: null },
  { id: "essay-guide-social-issues-3", topicText: "The weaker sections of Indian Society - are their Rights and Access to Justice getting Better?", category: "Social Issues", source: "guidance", year: null },
  { id: "essay-guide-social-issues-4", topicText: "Women's Empowerment: Progress, challenges, and future prospects", category: "Social Issues", source: "guidance", year: null },
  { id: "essay-guide-social-issues-5", topicText: "Education for Sustainable Development: Nurturing responsible citizens", category: "Social Issues", source: "guidance", year: null },
  { id: "essay-guide-social-issues-6", topicText: "Urbanization and Social Change: Balancing development and inclusivity", category: "Social Issues", source: "guidance", year: null },
  { id: "essay-guide-social-issues-7", topicText: "Privacy in the Digital Age", category: "Social Issues", source: "guidance", year: null },
  { id: "essay-guide-social-issues-8", topicText: "Mental Health Awareness: Bridging gaps in healthcare", category: "Social Issues", source: "guidance", year: null },
  { id: "essay-guide-social-issues-9", topicText: "Tribal Rights and Development: Addressing disparities and preserving cultures", category: "Social Issues", source: "guidance", year: null },
  { id: "essay-guide-social-issues-10", topicText: "Education without empathy is mere instruction", category: "Social Issues", source: "guidance", year: null },
  { id: "essay-guide-social-issues-11", topicText: "Loneliness in a connected age is a wound the algorithm cannot heal", category: "Social Issues", source: "guidance", year: null },
  { id: "essay-guide-social-issues-12", topicText: "India's strength lies in its plurality, not its uniformity", category: "Social Issues", source: "guidance", year: null },
  { id: "essay-guide-social-issues-13", topicText: "The wealth of a nation is the wellbeing of its weakest", category: "Social Issues", source: "guidance", year: null },
  { id: "essay-guide-social-issues-14", topicText: "Social Media, FOMO and Youth Loneliness", category: "Social Issues", source: "guidance", year: null },
  { id: "essay-guide-social-issues-15", topicText: "Caste persists because economics has not replaced it", category: "Social Issues", source: "guidance", year: null },
  { id: "essay-guide-social-issues-16", topicText: "The girl child is still a budget line, not a citizen", category: "Social Issues", source: "guidance", year: null },
  { id: "essay-guide-social-issues-17", topicText: "Ageing India: a problem we have not begun to name", category: "Social Issues", source: "guidance", year: null },
  { id: "essay-guide-social-issues-18", topicText: "Marriage as an institution is being renegotiated, not rejected", category: "Social Issues", source: "guidance", year: null },
  { id: "essay-guide-social-issues-19", topicText: "Welfare for the disabled: compassion or constitutional duty?", category: "Social Issues", source: "guidance", year: null },
  { id: "essay-guide-social-issues-20", topicText: "Mental health is public health", category: "Social Issues", source: "guidance", year: null },
  { id: "essay-guide-social-issues-21", topicText: "The declining village and the discontented city", category: "Social Issues", source: "guidance", year: null },
  { id: "essay-guide-social-issues-22", topicText: "A society is measured by how it treats its strangers", category: "Social Issues", source: "guidance", year: null },
  { id: "essay-guide-social-issues-23", topicText: "Identity politics: liberator or fragmenter?", category: "Social Issues", source: "guidance", year: null },
  { id: "essay-guide-social-issues-24", topicText: "Indian middle class — the conscience that lost its voice", category: "Social Issues", source: "guidance", year: null },
  { id: "essay-guide-social-issues-25", topicText: "Social justice without development is unsustainable", category: "Social Issues", source: "guidance", year: null },
  { id: "essay-guide-social-issues-26", topicText: "Poverty is more than just lack of money", category: "Social Issues", source: "guidance", year: null },
  { id: "essay-guide-international-relations-1", topicText: "India's Role in Global Governance: Opportunities and challenges", category: "International Relations", source: "guidance", year: null },
  { id: "essay-guide-international-relations-2", topicText: "Border Disputes and Diplomacy: Seeking peaceful resolutions", category: "International Relations", source: "guidance", year: null },
  { id: "essay-guide-international-relations-3", topicText: "Refugee Crisis and Global Responsibility: Humanitarian considerations", category: "International Relations", source: "guidance", year: null },
  { id: "essay-guide-international-relations-4", topicText: "Soft Power Diplomacy: Leveraging culture, education, and technology", category: "International Relations", source: "guidance", year: null },
  { id: "essay-guide-international-relations-5", topicText: "Cyber Diplomacy: Managing international relations in the digital realm", category: "International Relations", source: "guidance", year: null },
  { id: "essay-guide-international-relations-6", topicText: "To preserve heritage is to participate in the future", category: "International Relations", source: "guidance", year: null },
  { id: "essay-guide-international-relations-7", topicText: "Borders are drawn on maps; bridges are built between hearts", category: "International Relations", source: "guidance", year: null },
  { id: "essay-guide-international-relations-8", topicText: "Neighbourhood first, but not at any cost", category: "International Relations", source: "guidance", year: null },
  { id: "essay-guide-international-relations-9", topicText: "India's soft power: myth or muscle?", category: "International Relations", source: "guidance", year: null },
  { id: "essay-guide-international-relations-10", topicText: "The Global South speaks, but does anyone listen?", category: "International Relations", source: "guidance", year: null },
  { id: "essay-guide-international-relations-11", topicText: "Civilisation, not nation: India's long horizon", category: "International Relations", source: "guidance", year: null },
  { id: "essay-guide-international-relations-12", topicText: "The Indo-Pacific is a geography of intentions", category: "International Relations", source: "guidance", year: null },
  { id: "essay-guide-international-relations-13", topicText: "Diaspora as foreign policy", category: "International Relations", source: "guidance", year: null },
  { id: "essay-guide-international-relations-14", topicText: "A multipolar world without multipolar institutions is unstable", category: "International Relations", source: "guidance", year: null },
  { id: "essay-guide-international-relations-15", topicText: "Geopolitics in the era of AI and algorithms", category: "International Relations", source: "guidance", year: null },
  { id: "essay-guide-international-relations-16", topicText: "Global leadership in a fractured world", category: "International Relations", source: "guidance", year: null },
  { id: "essay-guide-international-relations-17", topicText: "India and its soft power diplomacy", category: "International Relations", source: "guidance", year: null },
  { id: "essay-guide-international-relations-18", topicText: "From globalism to nationalism: A policy shift", category: "International Relations", source: "guidance", year: null },
  { id: "essay-guide-international-relations-19", topicText: "United Nations at 80: Reform or redundancy?", category: "International Relations", source: "guidance", year: null },
  { id: "essay-guide-international-relations-20", topicText: "Global challenges require global solutions", category: "International Relations", source: "guidance", year: null },
  { id: "essay-guide-international-relations-21", topicText: "India's voice is rising on the world stage", category: "International Relations", source: "guidance", year: null },
  { id: "essay-guide-international-relations-22", topicText: "Cultural diplomacy is as important as economic diplomacy", category: "International Relations", source: "guidance", year: null },
  { id: "essay-guide-ethics-and-values-1", topicText: "Role of Integrity in Public Service: Upholding ethical standards", category: "Ethics and Values", source: "guidance", year: null },
  { id: "essay-guide-ethics-and-values-2", topicText: "Corporate Ethics and Social Responsibility: Balancing profit and impact", category: "Ethics and Values", source: "guidance", year: null },
  { id: "essay-guide-ethics-and-values-3", topicText: "Ethical Considerations in Artificial Intelligence: Balancing progress and responsibility", category: "Ethics and Values", source: "guidance", year: null },
  { id: "essay-guide-ethics-and-values-4", topicText: "Media Ethics in the Age of Misinformation: Nurturing responsible journalism", category: "Ethics and Values", source: "guidance", year: null },
  { id: "essay-guide-ethics-and-values-5", topicText: "Power tends to corrupt; absolute power corrupts absolutely", category: "Ethics and Values", source: "guidance", year: null },
  { id: "essay-guide-ethics-and-values-6", topicText: "Transparency and accountability are the foundations of trust", category: "Ethics and Values", source: "guidance", year: null },
  { id: "essay-guide-security-and-defense-1", topicText: "Nuclear Disarmament: India's stance and global implications", category: "Security and Defense", source: "guidance", year: null },
  { id: "essay-guide-security-and-defense-2", topicText: "Cyber Warfare and National Security: Preparing for digital threats", category: "Security and Defense", source: "guidance", year: null },
  { id: "essay-guide-security-and-defense-3", topicText: "Counterterrorism Strategies: International cooperation and domestic measures", category: "Security and Defense", source: "guidance", year: null },
  { id: "essay-guide-social-media-and-society-1", topicText: "Social Media and Political Activism: The power and limitations", category: "Social Media and Society", source: "guidance", year: null },
  { id: "essay-guide-social-media-and-society-2", topicText: "Online Privacy Concerns: Balancing security and individual rights", category: "Social Media and Society", source: "guidance", year: null },
  { id: "essay-guide-social-media-and-society-3", topicText: "Influence of Social Media on Youth: Impact on attitudes and behavior", category: "Social Media and Society", source: "guidance", year: null },
  { id: "essay-guide-social-media-and-society-4", topicText: "Deepfakes and Misinformation: Challenges to digital trust", category: "Social Media and Society", source: "guidance", year: null },
  { id: "essay-guide-social-media-and-society-5", topicText: "Social Media Influencers and Consumer Culture: Impact on societal values", category: "Social Media and Society", source: "guidance", year: null },
  { id: "essay-guide-human-rights-and-social-justice-1", topicText: "Right to Internet Access: Bridging the digital divide", category: "Human Rights and Social Justice", source: "guidance", year: null },
  { id: "essay-guide-human-rights-and-social-justice-2", topicText: "Combating Human Trafficking: Strategies for prevention and intervention", category: "Human Rights and Social Justice", source: "guidance", year: null },
  { id: "essay-guide-human-rights-and-social-justice-3", topicText: "Disability Rights and Inclusion: Creating accessible societies", category: "Human Rights and Social Justice", source: "guidance", year: null },
  { id: "essay-guide-human-rights-and-social-justice-4", topicText: "Reproductive Rights: Ensuring women's health and autonomy", category: "Human Rights and Social Justice", source: "guidance", year: null },
  { id: "essay-guide-human-rights-and-social-justice-5", topicText: "Indigenous Rights: Safeguarding the rights and cultures of indigenous communities", category: "Human Rights and Social Justice", source: "guidance", year: null },
  { id: "essay-guide-environment-1", topicText: "Climate change: Are we doing enough?", category: "Environment", source: "guidance", year: null },
  { id: "essay-guide-environment-2", topicText: "Man vs Nature: A conflict or coexistence?", category: "Environment", source: "guidance", year: null },
  { id: "essay-guide-environment-3", topicText: "Sustainable development is the only way forward", category: "Environment", source: "guidance", year: null },
  { id: "essay-guide-environment-4", topicText: "Environmental degradation and its impact on the poor", category: "Environment", source: "guidance", year: null },
  { id: "essay-guide-environment-5", topicText: "Can technology save the environment?", category: "Environment", source: "guidance", year: null },
  { id: "essay-guide-environment-6", topicText: "Climate Change Adaptation: Resilience strategies for vulnerable regions", category: "Environment", source: "guidance", year: null },
  { id: "essay-guide-environment-7", topicText: "Wildlife Conservation: Balancing conservation and development", category: "Environment", source: "guidance", year: null },
  { id: "essay-guide-environment-8", topicText: "Water Management in India: Sustainable use and conservation", category: "Environment", source: "guidance", year: null },
  { id: "essay-guide-environment-9", topicText: "Air Pollution Control: Strategies for cleaner air in urban areas", category: "Environment", source: "guidance", year: null },
  { id: "essay-guide-environment-10", topicText: "Plastic Waste Management: Reducing environmental impact", category: "Environment", source: "guidance", year: null },
  { id: "essay-guide-environment-11", topicText: "Climate change is the moral examination of our generation", category: "Environment", source: "guidance", year: null },
  { id: "essay-guide-environment-12", topicText: "Forests are not lungs; they are libraries", category: "Environment", source: "guidance", year: null },
  { id: "essay-guide-environment-13", topicText: "Water will be the oil of the 21st century", category: "Environment", source: "guidance", year: null },
  { id: "essay-guide-environment-14", topicText: "Climate justice is the new non-alignment", category: "Environment", source: "guidance", year: null },
  { id: "essay-guide-environment-15", topicText: "The Himalayas are a nation, not a backdrop", category: "Environment", source: "guidance", year: null },
  { id: "essay-guide-environment-16", topicText: "Plastic is a philosophy before it is a pollutant", category: "Environment", source: "guidance", year: null },
  { id: "essay-guide-environment-17", topicText: "Rewilding: can India reclaim what it lost?", category: "Environment", source: "guidance", year: null },
  { id: "essay-guide-environment-18", topicText: "A coastline is a country; we have not finished reading it", category: "Environment", source: "guidance", year: null },
  { id: "essay-guide-environment-19", topicText: "Net-zero without net-equity is a moral fraud", category: "Environment", source: "guidance", year: null },
  { id: "essay-guide-environment-20", topicText: "India's growth cannot be at the cost of nature", category: "Environment", source: "guidance", year: null },
  { id: "essay-guide-environment-21", topicText: "Climate change can neither be ignored nor reversed overnight", category: "Environment", source: "guidance", year: null },
  { id: "essay-guide-environment-22", topicText: "Sustainable development is a necessity, not a choice", category: "Environment", source: "guidance", year: null },
];
